from mongoengine import BooleanField, FloatField, IntField, StringField

from common.models import BaseDocument


class StudySession(BaseDocument):
    """A single study block on a specific day (generated by the planner)."""

    meta = {"collection": "study_sessions", "indexes": ["user_id", "date"]}

    SESSION_TYPES = ["study", "break", "revision"]

    user_id = StringField(required=True)
    subject_id = StringField()
    topic_id = StringField()
    subject_name = StringField(max_length=120, blank=True)
    topic_name = StringField(max_length=200, blank=True)
    date = StringField(required=True)  # YYYY-MM-DD
    start_time = StringField(required=True)  # HH:MM
    end_time = StringField(required=True)  # HH:MM
    duration = IntField(required=True)  # minutes
    session_type = StringField(choices=SESSION_TYPES, default="study")
    status = StringField(default="pending")  # pending | completed | missed
    is_break = BooleanField(default=False)
    priority_score = FloatField()
    label = StringField(max_length=200, blank=True)

    def to_dict(self):
        data = super().to_dict()
        data["duration"] = int(self.duration or 0)
        return data
